name: ci

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Clean
      run: go clean

    - name: Dependencies
      run: go get ./...

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build

    - name: Test
      run: go test

    - name: Lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.1
        golangci-lint run --timeout 2m0s

